version: 2

jobs:
  build:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - run:
          name: rustfmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: clippy
          command: |
            cargo clippy --version
            cargo clippy --all-features
      - run:
          name: audit
          command: |
            cargo audit --version
            cargo audit
      - run:
          name: build
          command: |
            rustc --version
            cargo --version
            cargo build
      - run:
          name: build --release
          command: |
            rustc --version
            cargo --version
            cargo build --release

  tests:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - run:
          name: test --all-features
          command: |
            rustc --version
            cargo --version
            cargo test --lib --all-features

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - tests
