[package]
name = "ledger-zcash"
description = "Library to integrate with the Ledger Zcash app"
version = "0.0.5"
license = "Apache-2.0"
authors = ["Zondax GmbH <info@zondax.ch>"]
homepage = "https://github.com/Zondax/ledger-zcash-rs"
repository = "https://github.com/Zondax/ledger-zcash-rs"
readme = "README.md"
categories = ["authentication", "cryptography"]
keywords = ["ledger", "nano", "apdu", "zcash"]
edition = "2018"
autobenches = false

[badges]
circle-ci = { repository = "zondax/ledger-zcash-rs" }

[lib]
name = "ledger_zcash"

[dependencies]
byteorder = "1.4.2"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.22"
log = "0.4.11"
zx-bip44 = "0.1.0"
ledger-zondax-generic = "0.7.0"
ledger-transport = "0.7.0"
ledger-transport-hid = "0.7.0"
hex = "0.4.2"
jubjub = { version = "0.5.1", default-features = false }
secp256k1 = { version = "0.19.0", default-features = false }
group = "0.8.0"
sha2 = "0.9.2"

zcash-hsmbuilder = { path = "../zcash-hsmbuilder", version = "0.0.5" }

[dependencies.zcash_primitives]
version = "0.4.0"
features = ["transparent-inputs"]

[dev-dependencies]
futures = "0.3.8"
matches = "0.1.8"
serial_test = "0.5.1"
env_logger = "0.8.2"
tokio = { version = "0.2", features = ["full"] }
tokio-test = "0.3.0"
